### ISSUE TITLE
Export without specifying destination?

### ISSUE THREAD

**Issue by homerlex** [eltoroit/ETCopyData#11]
As I mentioned in #4, when we do an export we won't know the destination yet.  The imports will be done at a later time against an org that is yet to be created.  Is there any reason you don't allow the destination to be blank when running an export (as of version 0.4.3)?

**Comment by eltoroit** [comment]
I decided the easiest way for exporting data was that you would not have to specify the fields you wanted, but the tool would be smart enough to know which fields it would extract. The logic is to check which fields are common in both environments (source, destination) and only export what can be imported. This means I need to know both orgs.

**Comment by homerlex** [comment]
It would be great if there were an option to assume all fields will be available in the destination and therefore not have to specify a destination.  In our use case we know the schema of the destination will match the source's schema.

**Comment by AikeaGuinea** [comment]
I also think it would be nice to be able to simply dump the data present in a sandbox/scratchorg directly to files, and even be able to 'import' from files.
If the files are part of the project, you can instantiate a scratchorg, deploy code and import data from your project, make changes to both project and data, then sync back to the repo.

**Comment by OscarScholten** [comment]
A trick that I use to import data from a set of files without having to refer to another Org is to use the alias as the source, and the full username as the destination:

In a bash script it looks like this:

```
ALIAS=`sfdx force:user:display -u $USER -v $DEVHUB | grep "^Username" | sed "s/Username *//" ; exit ${PIPESTATUS[0]}`
if [ $? -ne 0 ]; then
    exitFailure
fi

echo Starting data import
export NODE_OPTIONS=--max-old-space-size=8192
sfdx ETCopyData:import -s $USER -d $ALIAS -c "datasets/$DATAFOLDER"
if [ $? -ne 0 ]; then
    exitFailure
fi
```

$USER is read from the script parameters

**Comment by eltoroit** [comment]
Agree with @OscarScholten, your ETCopyData.json file could look like this:

```
"orgSource": "test-obtckbca2nde@example.com",
"orgDestination": "soTest",
```

Where one unique scratch org has the username assigned as "test-obtckbca2nde@example.com" and the alias as "soTest". but it's basically the same org ;-)

**Comment by homerlex** [comment]
FYI - I've just been using the same alias for both the source and destination.
