### ISSUE TITLE
Import without Authenticating the orgSource?

### ISSUE THREAD

**Issue by homerlex** [eltoroit/ETCopyData#13]
Sort of related to #11, in our use case the code executing our imports may not have access to the org specified as the orgSource.  If I try to import and do not have access to the orgSource I get an error like:

```
No AuthInfo found for name SourceData
```

Is there a reason you try to auth the orgSource during import?  If there is a reason, would it be possible to have an option to forego that auth?

Again, in our use case we know both the source and destination will have the same schema.

**Comment by jarrettkuljis** [comment]
In the context of continuous integration, and having the data resident locally, it would be ideal to not require the source org.  However there may be good reasons for this.  What is the downside of ignoring the source org when the data is resident locally?

**Comment by homerlex** [comment]
One reason I believe is how the import deals with record types.  We've been getting along in a hacky way specifying both the source and destination as the same org.  But now that I added data with record types its busted.  Looks like the current code needs to know both the source  and destination during the import in order to map the record types.  Is this correct?

**Comment by eltoroit** [comment]
```
"orgSource": "test-obtckbca2nde@example.com",
"orgDestination": "soTest",
```

Where one unique scratch org has the username assigned as "test-obtckbca2nde@example.com" and the alias as "soTest". but it's basically the same org ;-)
