### ISSUE TITLE
When specifying --json the only output should be the json results

### ISSUE THREAD

**Issue by homerlex** [eltoroit/ETCopyData#14]
When putting the --json option in the command the only output should in json.  I have an automated system running that executes sfdx commands and parses the output (expecting only json).  

If I don't specify a --loglevel it appears to be giving me TRACE level logging.  Is there no way to turn logging completely off?

Also, if I specify --loglevel=error I get no JSON output.  All I get is:
```
ETCopyData:Import... /
```
^ BTW I don't want the above message to appear at all when I specify --json.

**Comment by eltoroit** [comment]
This should be an wast fix

**Comment by eltoroit** [comment]
Just perform this call

```
sfdx ETCopyData:full -c EXFiles/data --json
```

And I get nothing but a Json output.
