### ISSUE TITLE
add support for circular and self references

### ISSUE THREAD

**Issue by OscarScholten** [eltoroit/ETCopyData#17]
Hi,

We've been evaluating ETCopyData for the development of our application and it seems to be a good fit! Two features that seems to be missing is the capability to import SObjects that have potentially circular references or that have references within the same SObject to form a tree. In our data model we have several cases where SObject A has a reference to SObject B, and B has a reference to A as well. We've not been able to import these types of fields.

Can you confirm that this is indeed not possible?

We're happy to contribute an initial feature to support this. Ideally, ETCopyData would be able to detect these types of relationships automatically, but that could be quite expensive, so preferably you would run that analysis once and then configure it somehow. We propose to implement for now just the step where the user would configure the fields that are circular or self-referencing. ETCopyData will then first load all SObjects with all configured fields except those "special" reference fields, and once all SObjects are loaded, ETCopyData will upsert the relevant records to restore the circular and self-referencing relationships.

We propose the configuration field "twoPassReferenceFields".

One possible future extension is to also support reference fields that are "required". The proposed solution does not support required reference fields as it first loads the fields with a "null" value.

Another future improvement is to optimize self-referencing fields that do not result in any cycles, these can be loaded in one step by first sorting the records in-memory and inserting them in the correct order.

Before we start on this work, do you have any feedback for us?

Cheers, Oscar Scholten

**Comment by eltoroit** [comment]
Oscar, I am glad ETCopyData May help you in your projects.

Other people have created issues on this repo about the fact that it does not handle recursive relationships, either within the same SObject (account hierarchy for example) or between different sObjects (A>B and B>A). I am not sure if anybody has made any changes to their own fork, because I have not been asked or notified. If you complete this task I would appreciate a pull request to benefit the whole community.

There are few reasons the original code does not handle recursive relationships, and they include:

- I did not have more time to work on this repo
- I do not require recursive relationships

I do not think that implementing recursive relationships is that complicated but there are few things that need to be considered:

- In which order to load the records 
- how many iterations to go?

With regards to the order, of A => B and B=> C and C=> A, which object do you load first? The solution that I have come with, is that it need to be an iterative process.

1. Load orphan records from A,B and C (those whose parent record is is null)
2. Get the newly created Id for each record and go through the remaining records in the table searching for the original Id and replace it with the new Id.
3. Insert the records that you already have parents for.
4 Rinse, wash, repeat...

There are several things that need to be considered?

1. How many times do you repeat? For example, in a parent/child self-relationship (account hierarchy)... how many generations do you go through?
2. What happens if there is a loop and accidentally or on purpose, the grandchild is the parent of the grand parent?
3. What if you have a complex relationships with several relationships and they are cyclical.

As you can start imagining, a generic solution is very complex to solve but not imposible... just make some assumptions of the data...

Please, if you do get time to work on this solution donanpull request so other users may benefit.

**Comment by eltoroit** [comment]
I do not quite follow the second issue, do you mind clarifying...

**Comment by OscarScholten** [comment]
Hi Andres,

Thank you for your feedback. I fully intend to make pull request once this work is complete, and would appreciate any feedback you may have.

The approach that I am taking now does not require any cycles, but in all fairness does leave room for performance improvements. Let's say we have 4 SObject types: A, B, C and D; A has a reference field ref1 to B, B has a reference field ref2 to A, C has a reference field ref3 to itself, and D does not have any reference fields. It would be up to the developer to configure ref1, ref2 and ref3 as "twoPassReferenceFields" (a new configuration option for each SObject similar to ignoredFields". The export process would export those fields, and during the import the procedure will be:

1. Load all SObjects, as they are loaded now, but without the configured twoPassReferenceFields. After this step, those fields will be null.

1.

**Comment by OscarScholten** [comment]
Hi @eltoroit,

I have created an initial implementation in a branch in my own repo:

https://github.com/OscarScholten/ETCopyData/tree/twoPassReferenceFields

If you have a bit of time, I'd appreciate some feedback on the following:
- In all fairness, I am a newbee TypeScript developer, so any feedback on TypeScript in general is much appreciated.
- In `Importer.setTwoPassReferences`, any errors are merged with the errors from the regular import process on line 377 (Util.logResultsAdd), or should a new result operation be created for this step?
- In `SchemaDiscovery.addChild`, why is there the check `sObjName === child.childSObject` on line 346 afaik it is not possible for a parent-child relation to be reflexive?
- When writing this message I was again thinking about the new configuration variable `twoPassReferenceFields`, I simply am not happy about it. How about `circularReferenceFields`? I'll float it with my colleagues here as well.

For me here the next step is to further test the code internally, and no doubt fix a few bugs in the process. If you have any feedback I'll process that as well, and update the documentation in `README.md` to reflect the new configuration options. When that is all complete, I'll open a pull request for the whole lot if that is ok with you.

Cheers, Oscar

**Comment by eltoroit** [comment]
Oscar,

I did not reply to your original message but I basically like the idea. I think that a two-pass would be enough and you do not need to worry about looping as I was originally thinking. I was thinking of a loop if your relationships were built using a Master-Detail or required lookups but if you can have them be created empty, then the recursion (regardless of the levels) will be possible.

**Comment by eltoroit** [comment]
I'll address your bullets:

- I learned TypeScript while building this tool, so I may have more newbie mistakes.
- I think line 377 is fine. The errors while running your code are part of the IMPORT operation (a better import).
- Do not remember... Either of two things: A record in ObjB is a child of ObjB, self-relationships or hierarchy relationships. If that is not the case, then I like writing defensive code :-)
- I like "Two Pass Reference" better than circular. I probably mentioned "circular" in the past because I was thinking of required lookups or Master-Detail relationships. Where the data needs to be loaded in a circular fashion but your solution works very well if the foreign key is not a required field.

Thanks for helping fix the code, I like what I see so far and would appreciate a pull request. Once this is tested, and the pull request is complete I will update the entry on npm.

Thanks.

**Comment by homerlex** [comment]
@OscarScholten - What is the status of your multi-pass branch for dealing with circular references?

**Comment by OscarScholten** [comment]
Hi @homerlex apologies for a late reply. The code is working, you can find it here:

https://github.com/OscarScholten/ETCopyData/tree/twoPassReferenceFields

I've made some additional changes, which can be found on another branch, and that is the one that I and a few team mates use currently:

https://github.com/OscarScholten/ETCopyData/tree/wip

Two main additional features on that wip branch:
- exporting many objects no longer leads to error on max number of open cursors
- etcopydata returns non-zero status code on error

It is a bit of a mess to be honest, I will work on getting these two branches in sync with master in this repo, and on a proper pull request.

@eltoroit do you have time to work on getting these changes reviewed and merged the coming days/weeks?

**Comment by eltoroit** [comment]
I would love to add merge those pull requests. Thanks for working on this tool. Much appreciated.

**Comment by homerlex** [comment]
@OscarScholten - on the wip branch I get the following error during SchemaDiscover when it gets to my object with circular reference:
```
ERROR running Export:
```
(Notice the actual error is not shown.  --loglevel=trace when I run these commands)

When I run from the twoPassReferenceFields branch I get an error about having to configure the twoPassReferenceFields.   It would be nice if the error included the name of the object(s) it got stuck on.  

This first issue is that it seems the error reporting may have been broken in wip branch.

The next issue is that I set the twoPassReferenceFields but still get the error below.  Perhaps I am not using it properly?

This is my sObjectsData in ETCopyData.json:
```
"sObjectsData": [
        {
            "name": "Object1__c",
            "ignoreFields": "OwnerId,CreatedBy,CreatedDate,CurrencyIsoCode,RecordTypeId,CleanStatus",
            "maxRecords": -1,
            "orderBy": "Name",
            "twoPassReferenceFields": "SomeFieldinObject2__c",
            "where": null
        },
        {
            "name": "Object2__c",
            "ignoreFields": "OwnerId,CreatedBy,CreatedDate,RecordTypeId,CleanStatus,CurrencyIsoCode",
            "maxRecords": -1,
            "orderBy": "Name",
            "twoPassReferenceFields": "SomeFieldinObject1__c",
            "where": null
        }
    ]
```

This is the error that I get:
```
18:25:57.224Z   23      FATAL   Util:51                 *** Abort Counter: 2 ***
18:25:57.226Z   24      FATAL   Util:52                 "Error: Deadlock determining import order, most likely caused by circular or self reference, configure those fields as twoPassReferenceFields\n    at Function.throwError (C:\\wrk\\EtCopyDataCircular\\src\\@ELTOROIT\\Util.ts:55:9)\n    at SchemaOrder.findImportOrder (C:\\wrk\\EtCopyDataCircular\\src\\@ELTOROIT\\SchemaOrder.ts:22:11)\n    at SchemaDiscovery.writeInfo (C:\\wrk\
18:25:57.226Z   24.2    FATAL   Util:52                 \EtCopyDataCircular\\src\\@ELTOROIT\\SchemaDiscovery.ts:125:46)\n    at Settings_1.Settings.read.then.then.then.then.then.then.then.then (C:\\wrk\\EtCopyDataCircular\\src\\@ELTOROIT\\ETCopyData.ts:341:62)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
[Util:51][18:25:57.224Z]: *** Abort Counter: 2 ***
[Util:52][18:25:57.226Z]: "Error: Deadlock determining import order, most likely caused by circular or self reference, configure those fields as twoPassReferenceFields\n    at Function.throwError (C:\\wrk\\EtCopyDataCircular\\src\\@ELTOROIT\\Util.ts:55:9)\n    at SchemaOrder.findImportOrder (C:\\wrk\\EtCopyDataCircular\\src\\@ELTOROIT\\SchemaOrder.ts:22:11)\n    at SchemaDiscovery.writeInfo (C:\\wrk\
[Util:52][18:25:57.226Z]: \EtCopyDataCircular\\src\\@ELTOROIT\\SchemaDiscovery.ts:125:46)\n    at Settings_1.Settings.read.then.then.then.then.then.then.then.then (C:\\wrk\\EtCopyDataCircular\\src\\@ELTOROIT\\ETCopyData.ts:341:62)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
(node:29332) UnhandledPromiseRejectionWarning: Error
    at Function.throwError (C:\wrk\EtCopyDataCircular\src\@ELTOROIT\Util.ts:55:9)
    at Settings_1.Settings.read.then.then.then.then.then.then.then.then.then.catch (C:\wrk\EtCopyDataCircular\src\@ELTOROIT\ETCopyData.ts:349:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:29332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by homerlex** [comment]
@OscarScholten - FYI, I got my export working.  I was missing the namespace from my field names in the twoPassReferenceFields def.  Very cool stuff.

**Comment by homerlex** [comment]
@OscarScholten - Now that I have the export working I tried an import and get a failure like the following (on the twoPassReferenceFields branch):
```
     [java] 19:31:54.094Z       879     TRACE   Importer:321            [MyScratchOrg] Updating references for [Object2__c] (1 of 1)
     [java] 19:31:54.094Z       880     TRACE   Importer:333            [MyScratchOrg] mapping field [Object1__c] to SObject [Object1__c]
     [java] 19:31:54.095Z       881     TRACE   Importer:346            [MyScratchOrg] mapping field [Object1__c] for [a0o170000037FS1AAM]:[ a1117000001SfPDAA0] => [a110R000000icKuQAI]
     [java] 19:31:55.752Z       882     TRACE   Importer:370            [MyScratchOrg] Error updating references in [Object2__c] record #1, old Id [undefined]MISSING_ARGUMENT:Id not specified in an update call:--
     [java] 19:31:55.753Z       883     INFO    Importer:376            [MyScratchOrg] Updated references for [Object2__c]. Record count: [Good = 0, Bad = 1]
     [java] 19:31:55.754Z       884     FATAL   Importer:97             [MyScratchOrg] Importing records failed. SObjects: 1, records 1  
```

**Comment by homerlex** [comment]
@OscarScholten - I figured out what was causes the error reported above.  It has to do with one of the Sobject having a master-detail relationship with the other and which object you set the twoPassReferenceFields value on.

I have 2 SObjects:
**OrderItem__c** has property named OrderItemInfo__c which has a Lookup relationship with the OrderItemInfo__c SObject.

**OrderItemInfo__c** has property named OrderItem__c which has a Master-Detail relationship with the OrderItem__c SObject.

If I set the twoPassReferenceFields on the OrderItemInfo__c like the following:
```
    "sObjectsData": [
        {
            "name": "OrderItem__c",
            "ignoreFields": "OwnerId,CreatedBy,CreatedDate,CurrencyIsoCode,RecordTypeId,CleanStatus",
            "maxRecords": -1,
            "orderBy": "Name",
            "twoPassReferenceFields": "OrderItemInfo__c",
            "where": null
        },
        {
            "name": "OrderItemInfo__c",
            "ignoreFields": "OwnerId,CreatedBy,CreatedDate,CurrencyIsoCode,RecordTypeId,CleanStatus",
            "maxRecords": -1,
            "orderBy": "Name",
            "twoPassReferenceFields": "OrderItem__c",
            "where": null
        }
```

I get an error like:
```
17:48:35.730Z   27      TRACE   Importer:86             sObjects should be processed in this order: OrderItemInfo__c,OrderItem__c
17:48:35.731Z   28      TRACE   Importer:184            [ExportTestDestination1] Importing Sobject: [OrderItemInfo__c] (1 of 2)
17:48:37.389Z   29      ERROR   Importer:290            *** [ExportTestDestination1] Error importing [OrderItemInfo__c] record #1. REQUIRED_FIELD_MISSING:Required fields are missing: [OrderItem__c]:OrderItem__c --
17:48:37.391Z   30      INFO    Importer:297            [ExportTestDestination1] Imported [OrderItemInfo__c]. Record count: [Good = 0, Bad = 1]
17:48:37.393Z   31      TRACE   Importer:184            [ExportTestDestination1] Importing Sobject: [OrderItem__c] (2 of 2)
17:48:39.109Z   32      TRACE   Importer:285            [ExportTestDestination1] Successfully imported [OrderItem__c] record #1. Ids mapped: [a00S0000007Pc1fIAC] => [a010R0000071o1YQAQ]
17:48:39.110Z   33      INFO    Importer:297            [ExportTestDestination1] Imported [OrderItem__c]. Record count: [Good = 1, Bad = 0]
17:48:39.113Z   34      TRACE   Importer:321            [ExportTestDestination1] Updating references for [OrderItemInfo__c] (1 of 2)
17:48:39.114Z   35      TRACE   Importer:333            [ExportTestDestination1] mapping field [OrderItem__c] to SObject [OrderItem__c]
17:48:39.115Z   36      TRACE   Importer:346            [ExportTestDestination1] mapping field [OrderItem__c] for [a01S000000HGXXPIA5]:[ a00S0000007Pc1fIAC] => [a010R0000071o1YQAQ]
17:48:40.851Z   37      TRACE   Importer:370            [ExportTestDestination1] Error updating references in [OrderItemInfo__c] record #1, old Id [undefined]MISSING_ARGUMENT:Id not specified in an update call:--
17:48:40.853Z   38      INFO    Importer:376            [ExportTestDestination1] Updated references for [OrderItemInfo__c]. Record count: [Good = 0, Bad = 1]
```

(I get a similar error if I clear the twoPassReferenceFields for OrderItem__c)

However, if I only specify the twoPassReferenceFields for OrderItem__c, like the following, it works perfectly:
```
        {
            "name": "OrderItem__c",
            "ignoreFields": "OwnerId,CreatedBy,CreatedDate,CurrencyIsoCode,RecordTypeId,CleanStatus",
            "maxRecords": -1,
            "orderBy": "Name",
            "twoPassReferenceFields": "OrderItemInfo__c",
            "where": null
        },
        {
            "name": "OrderItemInfo__c",
            "ignoreFields": "OwnerId,CreatedBy,CreatedDate,CurrencyIsoCode,RecordTypeId,CleanStatus",
            "maxRecords": -1,
            "orderBy": "Name",
            "twoPassReferenceFields": "",
            "where": null
        }
```

Could you document a little about populating twoPassReferenceFields?  How do we know which SObjects in a circular reference to decorate?

I believe if both sides of the circular reference are Lookup relationships you can specify twoPassReferenceFields on both objects without having a problem.

**Comment by OscarScholten** [comment]
@homerlex glad to see you got it working! Documentation for usage of the new configuration setting is indeed something I need to work on before finalizing my the pull request. Also, I'll see if I can improve the error message you get when a circular reference is detected, indeed it should show the SObject name and field as a minimum.

In general, if you have two SObjects that reference each other through a single Lookup relationship, you only need to flag one of those fields as a twoPassReferenceField.

As an example, assume you have the following SObject and fields:

SObject A: field refB of type Lookup(B)
SObject B: field refA of type Lookup(A)

And you have configured A.refB as twoPassReferenceField.

ETCopyData determines an import order, based on the Lookup and Parent/Child relationships that are _not_ flagged as twoPassReferenceFields. It sorts the list of SObjects:

1. the SObjects that have no relationships to any other SObjects
2. the SObjects that only have relationships to group 1
3. the SObjects that have relationships to group 1 and/or 2
4. etc.

ETCopyData then loads the data for the SObjects in that order, keeping track of the mapping between Ids in the source set and the target system, so it can set those immediately when loading a set of records in a later group.

In the example, ETCopyData will execute the following steps:

1. load all records for SObject A (keeping the refB field null), keeping track of the mapping between Id in the source set and the Id in the target system
2. load all records for SObject B, setting the refA field correctly using the mapping, keeping track of the mapping the record Ids
3. revisit all SObject A records, and set the refB field

**Comment by OscarScholten** [comment]
@homerlex I've created some initial documentation, could you have a look at https://github.com/OscarScholten/ETCopyData/tree/twoPassReferenceFields section 'References'?

I'll open a pull request now as well.

**Comment by homerlex** [comment]
@eltoroit - What is the status of getting this into a release?  We've been running this circular reference code for a while with no issues.

**Comment by daveespo** [comment]
Hi @eltoroit  -- can you get this published in a release on NPM? We can't get the plugin installed in our CI system because we can't whitelist an unpublished plugin. i.e. the `unsignedPluginWhiteList.json` only allows you to specify plugin names, and installing from a github URL doesn't honor the whitelist

**Comment by eltoroit** [comment]
Good news...

I have thought about the idea of updating the package in npm and I was waiting to get some time, the problem is that as you know that is hard to get. But when I saw @daveespo message about the Github installation not working for him. then I decided to make out the time and get the package updated.

I have published a beta version of this package which can be installed from npm using this command...

`echo 'y' | sfdx plugins:install etcopydata@beta`

Please test this, and let me know if it's ready to be moved to production.

Since I was already spending some time with this package, I also updated the npm references to remove those audit messages.

Enjoy, and please let me know if this is now working.

**Comment by daveespo** [comment]
Thanks for doing this! I can confirm that I'm able to install the beta version of the plugin -- I am using the `unsignedPluginWhiteList.json` which works since the module is coming from NPM so the installation is just `sfdx plugins:install etcopydata@beta`
