### ISSUE TITLE
Exit Code Zero even if there is an ETCopyData Failure

### ISSUE THREAD

**Issue by homerlex** [eltoroit/ETCopyData#22]
FYI - I posted the same question in the Saleforce DX Chatter group

I found that the exit code from sfdx is sometimes zero even if there was a failure.  I'm using the ETCopyData plugin and I can't be sure if the problem is with the plugin or with sfdx itself.  What I know is that in version 6.52.2 of sfdx-cli I get an exit code of "1" when there is an error in ETCopyData.  With sfdx-cli 7.14 I get an exit code of zero.  Any thoughts?

**Comment by OscarScholten** [comment]
I also noticed that ETCopyData does not always return a non-zero exit code when it should. I've created a fix in the following commit that should find its way to master in this repo soon:

https://github.com/OscarScholten/ETCopyData/commit/274e1bc0b1911f9d05d4fbf8b01ed43d982cc0ce

**Comment by eltoroit** [comment]
@OscarScholten so that's what that error means? :-) Do you want to create a pull request?

**Comment by eltoroit** [comment]
@OscarScholten did your pull request fix this?

**Comment by OscarScholten** [comment]
No, I will do another pull request for this coming Monday

**Comment by eltoroit** [comment]
Thanks, @OscarScholten,  I made some changes yesterday and closed a few issues which were opened for a while.
