### ISSUE TITLE
Copying data from a managed package custom object

### ISSUE THREAD

**Issue by franckdepicardie** [eltoroit/ETCopyData#37]
Hello,

First of all, congratulation, this plugin is awesome. Simple to configure. Very Quick execution.

Also, I am facing a problem when trying to copy a specific object (a manage packaged one) from source to target.

Issue occurs on export for the moment (i replaced sensitive information with "<>" and "..."):

{
    "status": 1,
    "name": "SfdxError",
    "message": "Requested sObject [<customObjectManaged>] was not found in the Org",
    "exitCode": 1,
    "commandName": "Export",
    "stack": "SfdxError: Requested sObject [<customObjectManaged>] was not found in the Org\n    at Function.wrap (.../sfdxError.js:149:20)\n    at Export.catch (.../ETCopyData/node_modules/@salesforce/command/lib/sfdxCommand.js:269:67)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "warnings": []
}

Also, i can confirm you thant my users have access to these object in source and target as i can query them with developper console.

Thank you.

Regards,
Franck

**Comment by drewdarmond** [comment]
I've found that deleting the source and destination folders in the ETCopyData folder has helped with this before.

**Comment by eltoroit** [comment]
@franckdepicardie did the solution provided by @drewdarmond worked? If not, please send me the configuration file and I would like to take a look.

**Comment by eltoroit** [comment]
Apparently this is not an issue, so I am closing it.
