### ISSUE TITLE
Installation dependency warnings

### ISSUE THREAD

**Issue by acrosman** [eltoroit/ETCopyData#39]
During install several dependency issues come up:

```
> sfdx plugins:install etcopydata
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
warning etcopydata > @salesforce/command > @oclif/test > fancy-test > @types/nock@11.1.0: This is a stub types definition. nock provides its own type definitions, so you do not need this installed.
warning etcopydata > @salesforce/command > @salesforce/core > @salesforce/ts-sinon > sinon > @sinonjs/formatio > samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
warning "etcopydata > @oclif/command@1.5.18" has unmet peer dependency "@oclif/plugin-help@^2".
Installing plugin etcopydata... installed v0.4.4
```

Run on Windows 10 from within VSCode's terminal using PowerShell.

Subsequent runs directly in PowerShell only repeat the unmet peer dependency:
```
> sfdx plugins:install etcopydata
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
warning "etcopydata > @oclif/command@1.5.18" has unmet peer dependency "@oclif/plugin-help@^2".
Installing plugin etcopydata... installed v0.4.4
```

**Comment by eltoroit** [comment]
The new version beta deployed today should take care of this

`echo 'y' | sfdx plugins:install etcopydata@beta`

**Comment by acrosman** [comment]
Yes, it looks like this issue is resolved. Thank you.

**Comment by acrosman** [comment]
Actually I take that back. Looks like there are still related issues here:

```
> sfdx plugins:install etcopydata@beta                                                                                              
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
warning etcopydata > @salesforce/command > @salesforce/core > @salesforce/ts-sinon > sinon > @sinonjs/formatio > samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
warning "etcopydata > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2".
Installing plugin etcopydata... installed v0.5.1
```

**Comment by eltoroit** [comment]
Is there anything I could do? This seems to be an issue with the node modules I am using to build the project. There were some issues with the libraries I was using because I had old ones, but I do not think I can do much with the nested libraries... sorry.

**Comment by acrosman** [comment]
I am trying to figure that out. 

The new deprecation warning is definitely from sfdx core 
`warning etcopydata > @salesforce/command > @salesforce/core > @salesforce/ts-sinon > sinon > @sinonjs/formatio > samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
`

I _think_ if you moved the `@oclif/plugin-help@^2` from being a dev dependency to a regular dependency in the package.json file it would fix it.  I can send you a PR if you'd like.
