### ISSUE TITLE
Any way to dynamically assign the destination?

### ISSUE THREAD

**Issue by homerlex** [eltoroit/ETCopyData#4]
For automated testing we are writing scripts to:

- Create a new scratch org (via sfdx)
- Install packages into the new org
- Load data into the new org (this is where ETCopyData hopefully comes in)

The problem I am seeing is that you have to have the source and destination in the ETCoptData.json.  It would be great if there were a way to specify the destination on the command line.

Also, I'd like to be able to do an export with out knowing what the destination is going to be.  For example, I want to manually run the export to get the files ready for some org that won't exists until we are ready to run test.  Then, when we spin up the org (in our script) for testing we import the data that we have on hand from a previous export.  Any thoughts on being able to do something like this?

BTW - your post seems to indicate this is doable but I don't see how:

(https://medium.com/@ElToroIT/etcopydata-dd190f4e85f0)
> ETCopyData, which is fully configurable, has several steps: compare, export, delete and import. You can execute these steps at once, or if you prefer, you can export the data from one org, keep the data around and import it into multiple scratch orgs or sandboxes.

**Comment by homerlex** [comment]
Any thoughts on this one?

**Comment by eltoroit** [comment]
Enhancement deployed.
