### ISSUE TITLE
Custom Settings record migration

### ISSUE THREAD

**Issue by tehn-r** [eltoroit/ETCopyData#40]
Is there any option to migrate custom setting records? Because I could migrate it using cli `sfdx force:data:tree:export` and `sfdx force:data:tree:import` commands. It would be nice to have this option as well

**Comment by eltoroit** [comment]
Can you do this with SFDX? How?

**Comment by tehn-r** [comment]
As I described I could do it using 2 commands
`sfdx force:data:tree:export -q "SELECT Fields FROM CustomSetting__c" -x export-demo -d sfdx-out --plan -u source`
`sfdx force:data:tree:import --plan sfdx-out/export-demo-CustomSetting__c-plan.json -u destination`

**Comment by eltoroit** [comment]
I am closing this issue because this is not the idea of this plugin. Those custom settings can't be related to other objects (or vice versa), plus there is a solution for this using SFDX.
