### ISSUE TITLE
Never ending export when exporting account and opportunity

### ISSUE THREAD

**Issue by Mhinzey** [eltoroit/ETCopyData#42]
Hi,

I'm pretty now to SalesForce, trying to figure out about objects relationship.
So, i can't export Opportunity and Account at the same time (Saw a related post about it but didn't get an answer from it).
Tried to play with the ignore fields and reference fields but couldn't figure it out

Here is my json file and trace logs
`
{
    "now": "2020-03-09T15:16:05.247Z",
    "orgSource": "DevHub",
    "orgDestination": "dreamhouse-org",
    "sObjectsData": [
        {
            "name": "Opportunity",
            "fieldsToExport": "Name",
            "ignoreFields": "CreatedDate,CurrencyIsoCode,OwnerId,CreatedBy",
            "maxRecords": -1,
            "orderBy": "Name",
            "twoPassReferenceFields": "AccountId",
            "where": "Name = 'Banana sells'"
        },
        {
            "name": "Account",
            "fieldsToExport": "Name",
            "ignoreFields": "DandbCompanyId,CreatedDate,CurrencyIsoCode,OwnerId,CreatedBy",
            "maxRecords": -1,
            "orderBy": "Name",
            "twoPassReferenceFields": "SBQQ__DefaultOpportunity__c",
            "where": null
        }
    ],
    "sObjectsMetadata": [],
    "rootFolder": "./ETCopyData",
    "includeAllCustom": false,
    "stopOnErrors": false,
    "ignoreFields": "OwnerId, CreatedBy, CreatedDate, CurrencyIsoCode",
    "maxRecordsEach": null,
    "deleteDestination": true,
    "pollingTimeout": 10000
}

Timestamp       #       Level   Line Number     Description
15:16:05.214Z   1       TRACE   ETCopyData.js:17        Log level: trace
15:16:05.218Z   2       INFO    ETCopyData.js:19        ETCopyData:Full Process Started
15:16:05.219Z   3       TRACE   ETCopyData.js:33        Parameter: source [DevHub]
15:16:05.220Z   4       TRACE   ETCopyData.js:37        Parameter: destination [dreamhouse-org]
15:16:05.228Z   5       INFO    Settings.js:202         Configuration value for [orgSource] read from command line: DevHub
15:16:05.229Z   6       INFO    Settings.js:214         Configuration value for [orgDestination] read from command line: dreamhouse-org
15:16:05.230Z   7       INFO    Settings.js:289         Configuration value for [rootFolder]: ./ETCopyData
15:16:05.239Z   8       INFO    Settings.js:289         Configuration value for [ignoreFields]: OwnerId, CreatedBy, CreatedDate, CurrencyIsoCode
15:16:05.240Z   9       INFO    Settings.js:289         Configuration value for [deleteDestination]: true
15:16:05.241Z   10      INFO    Settings.js:289         Configuration value for [pollingTimeout]: 10000
15:16:05.242Z   11      INFO    Settings.js:225         Configuration value for [sObjectsData]: 2 sObjects found.
15:16:05.243Z   12      INFO    Settings.js:232         Configuration value for [sObjectsMetadata]: 0 sObjects found.
15:16:05.260Z   13      TRACE   ETCopyData.js:271       Configuration settings read.
15:16:05.461Z   14      INFO    OrgManager.js:27        [DevHub] Alias for username: [oli.drck@hotmail.com]
15:16:06.954Z   15      TRACE   SchemaDiscovery.js:229  [DevHub] Found sObject [Account].
15:16:06.956Z   16      TRACE   SchemaDiscovery.js:229  [DevHub] Found sObject [Opportunity].
15:16:07.528Z   17      INFO    OrgManager.js:27        [dreamhouse-org] Alias for username: [test-bl4lzqi0twsv@example.com]
15:16:08.577Z   18      TRACE   SchemaDiscovery.js:229  [dreamhouse-org] Found sObject [Account].
15:16:08.580Z   19      TRACE   SchemaDiscovery.js:229  [dreamhouse-org] Found sObject [Opportunity].
15:16:09.080Z   20      WARN    ETCopyData.js:243       There are some *field* differences between the orgs. 
15:16:09.082Z   21      WARN    ETCopyData.js:247       If the following fields do exist in the org, then check security (FLS) because they could be hidden, but for now those fields will be ignored.
15:16:09.083Z   22      WARN    ETCopyData.js:252       [DevHub] Field [Account.CustomerPriority__c] does not exist in [dreamhouse-org].
15:16:09.091Z   23      WARN    ETCopyData.js:252       [DevHub] Field [Account.SLA__c] does not exist in [dreamhouse-org].
15:16:09.093Z   24      WARN    ETCopyData.js:252       [DevHub] Field [Account.Active__c] does not exist in [dreamhouse-org].     
15:16:09.094Z   25      WARN    ETCopyData.js:252       [DevHub] Field [Account.NumberofLocations__c] does not exist in [dreamhouse-org].
15:16:09.095Z   26      WARN    ETCopyData.js:252       [DevHub] Field [Account.UpsellOpportunity__c] does not exist in [dreamhouse-org].
15:16:09.096Z   27      WARN    ETCopyData.js:252       [DevHub] Field [Account.SLASerialNumber__c] does not exist in [dreamhouse-org].
15:16:09.097Z   28      WARN    ETCopyData.js:252       [DevHub] Field [Account.SLAExpirationDate__c] does not exist in [dreamhouse-org].
15:16:09.104Z   29      WARN    ETCopyData.js:243       There are some *field* differences between the orgs. 
15:16:09.105Z   30      WARN    ETCopyData.js:247       If the following fields do exist in the org, then check security (FLS) because they could be hidden, but for now those fields will be ignored.
15:16:09.107Z   31      WARN    ETCopyData.js:252       [DevHub] Field [Opportunity.DeliveryInstallationStatus__c] does not exist in [dreamhouse-org].
15:16:09.108Z   32      WARN    ETCopyData.js:252       [DevHub] Field [Opportunity.TrackingNumber__c] does not exist in [dreamhouse-org].
15:16:09.110Z   33      WARN    ETCopyData.js:252       [DevHub] Field [Opportunity.OrderNumber__c] does not exist in [dreamhouse-org].
15:16:09.111Z   34      WARN    ETCopyData.js:252       [DevHub] Field [Opportunity.CurrentGenerators__c] does not exist in [dreamhouse-org].
15:16:09.112Z   35      WARN    ETCopyData.js:252       [DevHub] Field [Opportunity.MainCompetitors__c] does not exist in [dreamhouse-org].
15:16:09.114Z   36      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Account.CustomerPriority__c] ignored because Org mismatch  
15:16:09.119Z   37      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Account.SLA__c] ignored because Org mismatch
15:16:09.120Z   38      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Account.Active__c] ignored because Org mismatch
15:16:09.122Z   39      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Account.NumberofLocations__c] ignored because Org mismatch
15:16:09.123Z   40      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Account.UpsellOpportunity__c] ignored because Org mismatch 
15:16:09.124Z   41      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Account.SLASerialNumber__c] ignored because Org mismatch   
15:16:09.124Z   42      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Account.SLAExpirationDate__c] ignored because Org mismatch 
15:16:09.125Z   43      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Opportunity.DeliveryInstallationStatus__c] ignored because 
Org mismatch
15:16:09.127Z   44      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Opportunity.TrackingNumber__c] ignored because Org mismatch15:16:09.127Z   45      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Opportunity.OrderNumber__c] ignored because Org mismatch   
15:16:09.128Z   46      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Opportunity.CurrentGenerators__c] ignored because Org mismatch
15:16:09.129Z   47      TRACE   SchemaDiscovery.js:94   [DevHub] Field [Opportunity.MainCompetitors__c] ignored because Org mismatch
`

Regards,
Olivier

**Comment by eltoroit** [comment]
Is this still happening?

**Comment by eltoroit** [comment]
There is an org mismatch, please configure ETCopyData properly and try again.
