### ISSUE TITLE
Provide Support for Setting Bulk API Batch Size

### ISSUE THREAD

**Issue by jflorianrel** [eltoroit/ETCopyData#43]
Hi,

Seeing the following error when importing large amounts of data:

`ERROR running ETCopyData:import:  Failed to read request. Exceeded max size limit of 10000000`

Is there any way to set the Bulk API Batch Size?

**Comment by eltoroit** [comment]
Are you trying to load 10 million records?

**Comment by jflorianrel** [comment]
> Are you trying to load 10 million records?

Ha, no!  That refers to the size of the data sent to SF in characters.  Sending ~4000 records with lots of fields in our case exceeds the batch limit noted here:

https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_concepts_limits.htm

`A batch can contain a maximum of 10,000,000 characters for all the data in a batch.`

Had a quick look at the code and it looks like the loadOneSObjectData method in Importer.ts would need to be modified to split a load into multiple batches.  I.e, provide a bulk API batch size parameter value of 200.  Iterate over 1000 records and submit 5 batches of 200, making note of the batch IDs.  Close the job and then monitor each batch for completion.

**Comment by eltoroit** [comment]
Would you like to do a pull request?

**Comment by eltoroit** [comment]
Is this still an issue for you? Have you been able to work with a smaller data set? Why do you need so many records for testing?

**Comment by eltoroit** [comment]
I am thinking about rebuilding this using SOAP API; this may help solve your problem. I am thinking about SOAP because I have the feeling it would work much faster. Bulk API is great because it's asynchronous, meaning we do not have to wait for an answer... but we need to wait to get the Ids of the new records and use those on the child sObjects.

**Comment by eltoroit** [comment]
The new version supports SOAP API and it actually works faster than Bulk API. There is an option in the configuration file (ETCopyData.json).

**Comment by daveespo** [comment]
This new feature never made it into the README -- can you provide an example on how to use the Bulk API vs SOAP API or update the README to explain?
