### ISSUE TITLE
Beta NPM module is broken - Cannot find module 'lodash/core'

### ISSUE THREAD

**Issue by daveespo** [eltoroit/ETCopyData#44]
We use the beta channel of ETCopyData in our CI/CD workflows

Starting between late last night and this morning, we started seeing the following build failures:

```
There was a problem executing your sfdx command: Error: Cannot find module 'lodash/core'
     [java]     at Function._load (/usr/local/lib/sfdx/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
     [java]     at require (/usr/local/lib/sfdx/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
     [java]     at Object.<anonymous> (~/.local/share/sfdx/node_modules/jsforce/lib/api/analytics.js:8:9)
     [java]     at Module._compile (/usr/local/lib/sfdx/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
     [java] 
     [java]  Command: sfdx ETCopyData:import -c data/etcopydata -d robot.1594215224752@pt.com -s robot.1594215224752@pt.com --loglevel=trace --json
```

We made no changes to our application code and have reviewed the SFDX CLI release notes (and plugin versions) and the environment of our CI/CD container to make sure the versions haven't changed.

The one change is that the ETCopyData plugin has updated from 0.5.9b 

`Installing plugin etcopydata... installed v0.5.9b`

The last successful build shows it was 0.5.8b:

`Installing plugin etcopydata... installed v0.5.8b`

What was in 0.5.9b that could've broken lodash? 

Also, I need to point out how sloppy this release process is -- there's no git tag to match the NPM version -- no Github Issue to track the work.

**Comment by daveespo** [comment]
Stand by .. it might be this freshly filed bug: https://github.com/forcedotcom/cli/issues/464

**Comment by eltoroit** [comment]
I have made some code changes and that's the reason I update the beta version. I also found out yesterday that ETCopyData is not working in my CI/CD tools either.  Hopefully, the dependent library is fixed soon!

**Comment by eltoroit** [comment]
WRT, "I need to point out how sloppy this release process is". Sorry, this is a one-man show... :-)

**Comment by daveespo** [comment]
Can you promote the version that was previously tagged as 'beta' to the 'latest' so that we can discontinue our usage of the beta channel? We are using 'beta' so that we can pick up the features from #30  .. we've been using that for a year now without issue; I think it can be promoted to the 'latest' channel

**Comment by eltoroit** [comment]
Did you try this: echo 'y' | sfdx plugins:install etcopydata@0.5.8-b

**Comment by tfuda** [comment]
I work with @daveespo. We did try the above (down-revving the etcopydata package), and we still got the "cannot find lodash/core" error. I think at this point, it has been determined this is a problem with sfdx-cli, not ETCopyData. It appears to be due to the fact that the lodash maintainers put out their first release in a year and it has some bugs. It seems the sfdx-cli package didn't lock down their dependencies, thus causing it to pull in the new, buggy release of lodash.

**Comment by daveespo** [comment]
I realize this ticket went two different ways. 

Yes, the bug with SFDX CLI was not a result of the ETCopy plugin update on the beta channel.

However, I am taking issue with the clarity of what is actually in the beta vs. latest channels on NPM for this plugin and my general concern about an undocumented update breaking our CI/CD. My request is to merge the 'stable' code from the beta package into a new package on the latest channel and continue to do the experimental work for the ETCopy package on the beta channel. @eltoroit  -- can you promote the 0.5.8 package to the 'latest' on NPM?

**Comment by eltoroit** [comment]
@daveespo please understand this is not a Salesforce product, and it does not have support. I appreciate that you are using this tool for your projects, and I will keep making changes to it... but it's not a professional tool and it does not get support. Sorry.

Having said that, I use the tool a lot in my projects, and I fix the issues that I find are blocking me. For example, I recently fix these issues:
- If the source and the destination is the same org, the metadata (record types) was not working.
- Allow loading data into production, but do not allow to be deleted, and asking for a random number to prevent it going in a CI/CD script

**Comment by eltoroit** [comment]
I believe ti's working now, can you please test. Thanks

**Comment by daveespo** [comment]
Yes, confirmed, our builds are now succeeding
