### ISSUE TITLE
Export only relevant descendents

### ISSUE THREAD

**Issue by eranvaizel** [eltoroit/ETCopyData#45]
Hello,

This seems like a great plugin! But I'm aiming to export only relevant descendents and I'm not sure if that's possible. Example: I'd like to export one specific Account by its ID. But then, if I want to export only the Opportunities related to this Account, I don't see any possible configuration to do this. Of course, I could place where AccountId = <Same Account ID in Account Export> in the Opportunity where clause. But that'll only work for the second level. What would I do if I wanted to export a third level (e.g. OpportunityContactRoles)? Am I missing something, or it's simply not supported yet?

Many thanks!

**Comment by eltoroit** [comment]
Could you not do this?

Where Opportunity.AccountId = 'XXX'

**Comment by eranvaizel** [comment]
That would work just for the first level. But what if I wanted to export the further child levels? E.g. the related tasks of all the opportunities of all the accounts where Account Id = 'XXX' ?

**Comment by eltoroit** [comment]
Could you not do this?

Where Parent__r.GrandParent__r.GreatGrandParent__r.AccountId = 'XXX'

Changing the code for this is going to touch too many lines.
