### ISSUE TITLE
ERROR: DELETE_FAILED: "Your attempt to delete Sample Account for Entitlements could not be completed because it is associated with the following entitlements.: Sample Entitlement"

### ISSUE THREAD

**Issue by eltoroit** [eltoroit/ETCopyData#48]
I discovered that if your Dev Hub is a Spring '21 pre-release version, you get this error when loading the data if you want to delete existing data first.

```
DELETE_FAILED: "Your attempt to delete Sample Account for Entitlements could not be completed because it is associated with the following entitlements.: Sample Entitlement"
```

The problem is that Salesforce is now creating an entitlement record with a related account record as [explained in this knowledge article](https://help.salesforce.com/articleView?id=000356109&language=en_US&mode=1&type=1).

The workaround is to clear the entitlements before the data is loaded. You can do this, using this trick:

1. Create a new file named `Entitlement.json` with this contents:

```
{
    "fetched": 0,
    "records": [],
    "total": 0
}
```

2.  Modify the file named `ETCopyData.json` to include the Entitlements standard sObject. Under `sObjectsData` add this line:

```
{ "name": "Entitlement" }
```

**Comment by daveespo** [comment]
We're working a case through Support right now to get this documented as a bug -- there should be no Account records in a brand new scratch org unless you've specified you want demo data

In our case, we added a step in our scratch org build to delete the Entitlement and Account before doing the data import but your workaround is good if you don't already have a scripting solution to building scratch orgs
