### ISSUE TITLE
"./node_modules/sfdx-cli/bin/run" can't find the ETCopyData plugin

### ISSUE THREAD

**Issue by cventurini** [eltoroit/ETCopyData#55]
Hi, I've followed the intructions to run ETCopyData using sfdx. In other words, I've installed npm and then used the suggested import command: "./node_modules/sfdx-cli/bin/run ETCopyData import --configfolder ./xxxx/data --loglevel trace --json"

However, I'm getting a warning stating "ETCopyData import is not a sfdx command". I also noticed, I could not detect the installed plugin from sfdx (i.e. ./node_modules/sfdx-cli/bin/run plugins). It returned a "No plugins installed" message. I was able to verify the ETCopyData plugin was installed using "sf plugins". 

Update: Fixed the issue by uninstalling plugin from sf and installing in sfdx

**Comment by eltoroit** [comment]
That's what I was about to suggest... I need to update the READMe file

**Comment by eltoroit** [comment]
1. Clone the repository: `git clone https://github.com/eltoroit/ETCopyData.git`
2. Change directory `cd ETCopyData`
3. Install npm modules: `npm install --production`
4. Install SFDX CLI in your project: `npm i sfdx-cli@7.209.6`
5. Link the plugin: `./node_modules/sfdx-cli/bin/run plugins:link .`
6. Use the local SFDX version with ETCopyData

- Export Data: `./node_modules/sfdx-cli/bin/run ETCopyData export --configfolder ./@ELTOROIT/data --loglevel trace --json`
- Import Data: `./node_modules/sfdx-cli/bin/run ETCopyData import --configfolder ./@ELTOROIT/data --loglevel trace --json`
- Delete Data: `./node_modules/sfdx-cli/bin/run ETCopyData delete --configfolder ./@ELTOROIT/data --loglevel trace --json`
